# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'le2mBordereaux_gui_main.ui'
#
# Created: Sun Apr 19 18:27:21 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(682, 698)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_logo = QtGui.QLabel(self.centralwidget)
        self.label_logo.setText(_fromUtf8(""))
        self.label_logo.setPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/logo_lameta.gif")))
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.horizontalLayout_2.addWidget(self.label_logo)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_description = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_description.setObjectName(_fromUtf8("label_description"))
        self.horizontalLayout_2.addWidget(self.label_description)
        spacerItem1 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_nom = QtGui.QLabel(self.centralwidget)
        self.label_nom.setObjectName(_fromUtf8("label_nom"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_nom)
        self.lineEdit_nomExperience = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nomExperience.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_nomExperience.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_nomExperience.setObjectName(_fromUtf8("lineEdit_nomExperience"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_nomExperience)
        self.label_ville = QtGui.QLabel(self.centralwidget)
        self.label_ville.setObjectName(_fromUtf8("label_ville"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_ville)
        self.lineEdit_ville = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_ville.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_ville.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_ville.setObjectName(_fromUtf8("lineEdit_ville"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_ville)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.dateEdit)
        self.label_premierBordereau = QtGui.QLabel(self.centralwidget)
        self.label_premierBordereau.setObjectName(_fromUtf8("label_premierBordereau"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_premierBordereau)
        self.spinBox_premierBordereau = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_premierBordereau.setMaximum(999)
        self.spinBox_premierBordereau.setObjectName(_fromUtf8("spinBox_premierBordereau"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox_premierBordereau)
        self.horizontalLayout.addLayout(self.formLayout_2)
        spacerItem3 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.timeEdit)
        self.label_presents = QtGui.QLabel(self.centralwidget)
        self.label_presents.setObjectName(_fromUtf8("label_presents"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_presents)
        self.label_presents_nb = QtGui.QLabel(self.centralwidget)
        self.label_presents_nb.setObjectName(_fromUtf8("label_presents_nb"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_presents_nb)
        self.horizontalLayout.addLayout(self.formLayout_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableView_sujets = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_sujets.sizePolicy().hasHeightForWidth())
        self.tableView_sujets.setSizePolicy(sizePolicy)
        self.tableView_sujets.setMinimumSize(QtCore.QSize(550, 500))
        self.tableView_sujets.setMaximumSize(QtCore.QSize(350, 16777215))
        self.tableView_sujets.setDragEnabled(False)
        self.tableView_sujets.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableView_sujets.setAlternatingRowColors(True)
        self.tableView_sujets.setSortingEnabled(False)
        self.tableView_sujets.setObjectName(_fromUtf8("tableView_sujets"))
        self.tableView_sujets.horizontalHeader().setMinimumSectionSize(20)
        self.tableView_sujets.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_3.addWidget(self.tableView_sujets)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_add = QtGui.QPushButton(self.centralwidget)
        self.pushButton_add.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/plus_1.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon)
        self.pushButton_add.setObjectName(_fromUtf8("pushButton_add"))
        self.verticalLayout_2.addWidget(self.pushButton_add)
        self.pushButton_monter = QtGui.QPushButton(self.centralwidget)
        self.pushButton_monter.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/up.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_monter.setIcon(icon1)
        self.pushButton_monter.setObjectName(_fromUtf8("pushButton_monter"))
        self.verticalLayout_2.addWidget(self.pushButton_monter)
        self.pushButton_descendre = QtGui.QPushButton(self.centralwidget)
        self.pushButton_descendre.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/down.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_descendre.setIcon(icon2)
        self.pushButton_descendre.setObjectName(_fromUtf8("pushButton_descendre"))
        self.verticalLayout_2.addWidget(self.pushButton_descendre)
        self.pushButton_remove = QtGui.QPushButton(self.centralwidget)
        self.pushButton_remove.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/moins_1.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_remove.setIcon(icon3)
        self.pushButton_remove.setObjectName(_fromUtf8("pushButton_remove"))
        self.verticalLayout_2.addWidget(self.pushButton_remove)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuEdition = QtGui.QMenu(self.menubar)
        self.menuEdition.setObjectName(_fromUtf8("menuEdition"))
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName(_fromUtf8("menuAide"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_ouvrir = QtGui.QAction(MainWindow)
        self.action_ouvrir.setObjectName(_fromUtf8("action_ouvrir"))
        self.action_enregistrer = QtGui.QAction(MainWindow)
        self.action_enregistrer.setObjectName(_fromUtf8("action_enregistrer"))
        self.action_imprimer = QtGui.QAction(MainWindow)
        self.action_imprimer.setObjectName(_fromUtf8("action_imprimer"))
        self.action_quitter = QtGui.QAction(MainWindow)
        self.action_quitter.setObjectName(_fromUtf8("action_quitter"))
        self.action_bordereauVierge = QtGui.QAction(MainWindow)
        self.action_bordereauVierge.setObjectName(_fromUtf8("action_bordereauVierge"))
        self.action_ajouterSujet = QtGui.QAction(MainWindow)
        self.action_ajouterSujet.setObjectName(_fromUtf8("action_ajouterSujet"))
        self.action_viderListe = QtGui.QAction(MainWindow)
        self.action_viderListe.setObjectName(_fromUtf8("action_viderListe"))
        self.action_afficherAide = QtGui.QAction(MainWindow)
        self.action_afficherAide.setObjectName(_fromUtf8("action_afficherAide"))
        self.action_afficherPropos = QtGui.QAction(MainWindow)
        self.action_afficherPropos.setObjectName(_fromUtf8("action_afficherPropos"))
        self.menuFichier.addAction(self.action_ouvrir)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.action_enregistrer)
        self.menuFichier.addAction(self.action_imprimer)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.action_quitter)
        self.menuAide.addAction(self.action_afficherAide)
        self.menuAide.addAction(self.action_afficherPropos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Bordereau Editor", None))
        self.label_description.setText(_translate("MainWindow", "LE2M - Bordereaux", None))
        self.label_nom.setText(_translate("MainWindow", "Expérience", None))
        self.label_ville.setText(_translate("MainWindow", "Ville", None))
        self.label.setText(_translate("MainWindow", "Date", None))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy", None))
        self.label_premierBordereau.setText(_translate("MainWindow", "Premier Bordereau", None))
        self.label_2.setText(_translate("MainWindow", "Heure", None))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm", None))
        self.label_presents.setText(_translate("MainWindow", "Total présents:", None))
        self.label_presents_nb.setText(_translate("MainWindow", "0", None))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier", None))
        self.menuEdition.setTitle(_translate("MainWindow", "Edition", None))
        self.menuAide.setTitle(_translate("MainWindow", "Aide", None))
        self.action_ouvrir.setText(_translate("MainWindow", "Ouvrir", None))
        self.action_enregistrer.setText(_translate("MainWindow", "Enregistrer", None))
        self.action_imprimer.setText(_translate("MainWindow", "Imprimer", None))
        self.action_quitter.setText(_translate("MainWindow", "Quitter", None))
        self.action_bordereauVierge.setText(_translate("MainWindow", "Editer un bordereau vierge", None))
        self.action_ajouterSujet.setText(_translate("MainWindow", "Ajouter un sujet", None))
        self.action_viderListe.setText(_translate("MainWindow", "Vider la liste", None))
        self.action_afficherAide.setText(_translate("MainWindow", "Aide de Bordereau Editor", None))
        self.action_afficherPropos.setText(_translate("MainWindow", "A Propos", None))

