# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'le2mBordereaux_gui_main.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1129, 876)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/logo_ceem.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_logo = QtGui.QLabel(self.centralwidget)
        self.label_logo.setText(_fromUtf8(""))
        self.label_logo.setPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/logo_ceem.png")))
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.horizontalLayout_2.addWidget(self.label_logo)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_nom = QtGui.QLabel(self.centralwidget)
        self.label_nom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_nom.setObjectName(_fromUtf8("label_nom"))
        self.horizontalLayout.addWidget(self.label_nom)
        self.lineEdit_nomExperience = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nomExperience.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_nomExperience.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_nomExperience.setObjectName(_fromUtf8("lineEdit_nomExperience"))
        self.horizontalLayout.addWidget(self.lineEdit_nomExperience)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.dateEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_5.addWidget(self.dateEdit)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.timeEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.horizontalLayout_7.addWidget(self.timeEdit)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_ville = QtGui.QLabel(self.centralwidget)
        self.label_ville.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ville.setObjectName(_fromUtf8("label_ville"))
        self.horizontalLayout_4.addWidget(self.label_ville)
        self.lineEdit_ville = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_ville.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_ville.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_ville.setObjectName(_fromUtf8("lineEdit_ville"))
        self.horizontalLayout_4.addWidget(self.lineEdit_ville)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_premierBordereau = QtGui.QLabel(self.centralwidget)
        self.label_premierBordereau.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_premierBordereau.setObjectName(_fromUtf8("label_premierBordereau"))
        self.horizontalLayout_6.addWidget(self.label_premierBordereau)
        self.spinBox_premierBordereau = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_premierBordereau.setMinimumSize(QtCore.QSize(150, 0))
        self.spinBox_premierBordereau.setMaximumSize(QtCore.QSize(150, 16777215))
        self.spinBox_premierBordereau.setMaximum(999)
        self.spinBox_premierBordereau.setObjectName(_fromUtf8("spinBox_premierBordereau"))
        self.horizontalLayout_6.addWidget(self.spinBox_premierBordereau)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_presents = QtGui.QLabel(self.centralwidget)
        self.label_presents.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_presents.setObjectName(_fromUtf8("label_presents"))
        self.horizontalLayout_8.addWidget(self.label_presents)
        self.label_presents_nb = QtGui.QLabel(self.centralwidget)
        self.label_presents_nb.setObjectName(_fromUtf8("label_presents_nb"))
        self.horizontalLayout_8.addWidget(self.label_presents_nb)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 2, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.tableView_sujets = QtGui.QTableView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_sujets.sizePolicy().hasHeightForWidth())
        self.tableView_sujets.setSizePolicy(sizePolicy)
        self.tableView_sujets.setMinimumSize(QtCore.QSize(800, 600))
        self.tableView_sujets.setMaximumSize(QtCore.QSize(900, 16777215))
        self.tableView_sujets.setDragEnabled(False)
        self.tableView_sujets.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableView_sujets.setAlternatingRowColors(True)
        self.tableView_sujets.setSortingEnabled(False)
        self.tableView_sujets.setObjectName(_fromUtf8("tableView_sujets"))
        self.tableView_sujets.horizontalHeader().setMinimumSectionSize(20)
        self.tableView_sujets.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_3.addWidget(self.tableView_sujets)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_add = QtGui.QPushButton(self.centralwidget)
        self.pushButton_add.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/plus.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon1)
        self.pushButton_add.setObjectName(_fromUtf8("pushButton_add"))
        self.verticalLayout_2.addWidget(self.pushButton_add)
        self.pushButton_monter = QtGui.QPushButton(self.centralwidget)
        self.pushButton_monter.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/up.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_monter.setIcon(icon2)
        self.pushButton_monter.setObjectName(_fromUtf8("pushButton_monter"))
        self.verticalLayout_2.addWidget(self.pushButton_monter)
        self.pushButton_descendre = QtGui.QPushButton(self.centralwidget)
        self.pushButton_descendre.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/down.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_descendre.setIcon(icon3)
        self.pushButton_descendre.setObjectName(_fromUtf8("pushButton_descendre"))
        self.verticalLayout_2.addWidget(self.pushButton_descendre)
        self.pushButton_remove = QtGui.QPushButton(self.centralwidget)
        self.pushButton_remove.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../le2mBordereauxImages/moins.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_remove.setIcon(icon4)
        self.pushButton_remove.setObjectName(_fromUtf8("pushButton_remove"))
        self.verticalLayout_2.addWidget(self.pushButton_remove)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtGui.QSpacerItem(20, 14, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuEdition = QtGui.QMenu(self.menubar)
        self.menuEdition.setObjectName(_fromUtf8("menuEdition"))
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName(_fromUtf8("menuAide"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_ouvrir = QtGui.QAction(MainWindow)
        self.action_ouvrir.setObjectName(_fromUtf8("action_ouvrir"))
        self.action_enregistrer = QtGui.QAction(MainWindow)
        self.action_enregistrer.setObjectName(_fromUtf8("action_enregistrer"))
        self.action_imprimer = QtGui.QAction(MainWindow)
        self.action_imprimer.setObjectName(_fromUtf8("action_imprimer"))
        self.action_quitter = QtGui.QAction(MainWindow)
        self.action_quitter.setObjectName(_fromUtf8("action_quitter"))
        self.action_bordereauVierge = QtGui.QAction(MainWindow)
        self.action_bordereauVierge.setObjectName(_fromUtf8("action_bordereauVierge"))
        self.action_ajouterSujet = QtGui.QAction(MainWindow)
        self.action_ajouterSujet.setObjectName(_fromUtf8("action_ajouterSujet"))
        self.action_viderListe = QtGui.QAction(MainWindow)
        self.action_viderListe.setObjectName(_fromUtf8("action_viderListe"))
        self.action_afficherAide = QtGui.QAction(MainWindow)
        self.action_afficherAide.setObjectName(_fromUtf8("action_afficherAide"))
        self.action_afficherPropos = QtGui.QAction(MainWindow)
        self.action_afficherPropos.setObjectName(_fromUtf8("action_afficherPropos"))
        self.menuFichier.addAction(self.action_ouvrir)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.action_enregistrer)
        self.menuFichier.addAction(self.action_imprimer)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.action_quitter)
        self.menuAide.addAction(self.action_afficherAide)
        self.menuAide.addAction(self.action_afficherPropos)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuEdition.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Bordereau Editor", None))
        self.label_nom.setText(_translate("MainWindow", "Expérience", None))
        self.label.setText(_translate("MainWindow", "Date", None))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy", None))
        self.label_2.setText(_translate("MainWindow", "Heure", None))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm", None))
        self.label_ville.setText(_translate("MainWindow", "Ville", None))
        self.label_premierBordereau.setText(_translate("MainWindow", "Premier Bordereau", None))
        self.label_presents.setText(_translate("MainWindow", "Total présents:", None))
        self.label_presents_nb.setText(_translate("MainWindow", "0", None))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier", None))
        self.menuEdition.setTitle(_translate("MainWindow", "Edition", None))
        self.menuAide.setTitle(_translate("MainWindow", "Aide", None))
        self.action_ouvrir.setText(_translate("MainWindow", "Ouvrir", None))
        self.action_enregistrer.setText(_translate("MainWindow", "Enregistrer", None))
        self.action_imprimer.setText(_translate("MainWindow", "Imprimer", None))
        self.action_quitter.setText(_translate("MainWindow", "Quitter", None))
        self.action_bordereauVierge.setText(_translate("MainWindow", "Editer un bordereau vierge", None))
        self.action_ajouterSujet.setText(_translate("MainWindow", "Ajouter un sujet", None))
        self.action_viderListe.setText(_translate("MainWindow", "Vider la liste", None))
        self.action_afficherAide.setText(_translate("MainWindow", "Aide de Bordereau Editor", None))
        self.action_afficherPropos.setText(_translate("MainWindow", "A Propos", None))

